name: Deploy static content to Pages

on:
  # Runs on pushes or pull requests targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "include/**"
  pull_request:
    branches: ["main"]
    paths:
      - "include/**"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # Needed to commit generated docs
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate documentation
        run: doxygen Doxyfile

  deploy:
    needs: documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Commit documentation
        run: |
          git config --global user.name "KoniHD"
          git config --global user.email "konstantin.zeck+github@gmail.com"
          git add docs/
          git commit -m "Automatically update documentation" || echo "No changes to commit"
          git push git@github.com:KoniHD/stock_sim_uni.git main

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
